'use strict';

var routines = [
	{
		id:0,
		name:'Default',
		icon:'default.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/default',
			creator:'inipagistudio'
		},
		audio:'default',
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
		tasks:[
			{
				id:0,
				tasks:[
					{
						id:2,
						tasks:[
							{id:12},
							{id:13}
						]
					},
					{id:8}
				]
			},
			{
				id:1,
				tasks:[
					{id:3},
					{id:4},
					{id:5},
					{id:6},
					{id:7}
				]
			},
			{id:10},
			{id:11}
		]
	},
	{
		id:1,
		theme:
		{
			contentWrapper:{bg:"#AAAAFF",c:"#000000"}, 
			unstarted:{bg:"#999999",c:"#CCCCFF"}, 
			current:{bg:"#CCFFCC",c:"#000000"}, 
			completed:{bg:"#884444",c:"#662222"}, 
			notAllowed:{bg:"#FFCCCC",c:"#992222"}
		},
		name:'Loop Task Audio',
		loopAudio:true,
		loopDelay:2,
		icon:'repeat.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/music-and-multimedia',
			creator:'orvipixel'
		},
		tasks:[
			{id:28},
			{id:29},
			{
				id:30,
				tasks:[
					{id:31},
					{id:32}
				]
			}
		]
	},
	{
		id:2,
		name:'Timer Auto-Advance',
		autoAdvanceTimer:true,
		icon:'time.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/time',
			creator:'Ilham Fitrotul Hayat'
		},
		tasks:[
			{id:24},
			{
				id:21,
				tasks:[
					{id:22},
					{id:23}
				]
			},
			{
				id:17,
				tasks:[
					{id:18},
					{id:19},
					{id:20}
				]
			},
			{
				id:14,
				tasks:[
					{id:15},
					{id:16}
				]
			},
		]
	},
	{
		id:3,
		name:'Task Done Advance',
		autoAdvanceDone:true,
		icon:'todo.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/checklist',
			creator:'Freepik'
		},
		tasks:[
			{
				id:0,
				tasks:[
					{
						id:2,
						tasks:[
							{id:12},
							{id:13}
						]
					},
					{id:8}
				]
			},
			{
				id:1,
				tasks:[
					{id:3},
					{id:4},
					{id:5},
					{id:6},
					{id:7}
				]
			},
			{id:10},
			{id:11}
		]
	},
	{
		id:4,
		name:'Enforce Order',
		enforceChildrenOrder:true,
		reminderLimit:2,
		icon:'list.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/list',
			creator:'Freepik'
		},
		tasks:[
			{id:25},
			{id:26},
			{id:27}
		]
	},
	{
		id:5,
		name:'Hide Done',
		audio:'hideCompleted',
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
		icon:'completed.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/task',
			creator:'prettycons'
		},
		hideCompletedTasks:true,
		tasks:[
			{
				id:0,
				tasks:[
					{
						id:2,
						tasks:[
							{id:12},
							{id:13}
						]
					},
					{id:8}
				]
			},
			{
				id:1,
				tasks:[
					{id:3},
					{id:4},
					{id:5},
					{id:6},
					{id:7}
				]
			},
			{id:10},
			{id:11}
		]
	},
	{
		id:6,
		name:'Task Audio Prefix',
		taskAudioPrefix:'prefix',
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
		icon:'prefix.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/playlist',
			creator:'Freepik'
		},
		tasks:[
			{
				id:0,
				tasks:[
					{
						id:2,
						tasks:[
							{id:12},
							{id:13}
						]
					},
					{id:8}
				]
			},
			{
				id:1,
				tasks:[
					{id:3},
					{id:4},
					{id:5},
					{id:6},
					{id:7}
				]
			},
			{id:10},
			{id:11}
		]
	},
	{
		id:7,
		name:'Task Audio Suffix',
		taskAudioSuffix:'suffix',
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
		icon:'suffix.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/playlist',
			creator:'Freepik'
		},
		tasks:[
			{
				id:0,
				tasks:[
					{
						id:2,
						tasks:[
							{id:12},
							{id:13}
						]
					},
					{id:8}
				]
			},
			{
				id:1,
				tasks:[
					{id:3},
					{id:4},
					{id:5},
					{id:6},
					{id:7}
				]
			},
			{id:10},
			{id:11}
		]
	},
	{
		id:8,
		name:'Task Done Audio',
		audioEncouragement:'awesome',
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
		icon:'doneAudio.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/playlist',
			creator:'Royyan Wijaya'
		},
		tasks:[
			{
				id:0,
				tasks:[
					{
						id:2,
						tasks:[
							{id:12},
							{id:13}
						]
					},
					{id:8}
				]
			},
			{
				id:1,
				tasks:[
					{id:3},
					{id:4},
					{id:5},
					{id:6},
					{id:7}
				]
			},
			{id:10},
			{id:11}
		]
	},
	{
		id:9,
		name:'Time Expired Audio',
		timeExpiredAudio:'timer',
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
		icon:'clock.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/alarm-clock',
			creator:'Iconjam'
		},
		tasks:[
			{
				id:0,
				tasks:[
					{
						id:2,
						tasks:[
							{id:12},
							{id:13}
						]
					},
					{id:8}
				]
			},
			{
				id:1,
				tasks:[
					{id:3},
					{id:4},
					{id:5},
					{id:6},
					{id:7}
				]
			},
			{id:10},
			{id:11}
		]
	}
];

var tasks = [
	{
		id:0,
		text:'Breakfast Time',
		time:3,
		audio:'breakfast',
	},
	{
		id:1,
		text:'Get Dressed',
		time:300,
		audio:'dressed'
	},
	{
		id:2,
		text:'Oatmeal',
		time:300,
		audio:'eat',
		icon:'breakfast.png'
	},
	{
		id:3,
		text:'Underwear On',
		time:45,
		audio:'underwear'
	},
	{
		id:4,
		text:'Pants On',
		time:60,
		audio:'trousers'
	},
	{
		id:5,
		text:'Shirt On',
		time:50,
		audio:'shirt'
	},
	{
		id:6,
		text:'Long Sleeved Shirt On',
		time:50,
		audio:'longShirt'
	},
	{
		id:7,
		text:'Socks On',
		time:45,
		audio:'socks'
	},
	{
		id:8,
		text:'Drink Milk',
		time:120,
		audio:'milk'
	},
	{
		id:10,
		text:'Potty Try',
		time:300,
		audio:'potty'
	},
	{
		id:11,
		text:'Shoes On',
		time:120,
		audio:'shoes'
	},
	{
		id:12,
		text:'Cook Oatmeal',
		time:180,
		audio:'eat'
	},
	{
		id:13,
		text:'Eat Oatmeal',
		time:900,
		audio:'dishes'
	},
	{
		id:14,
		text:'Cardio',
		time:1800
	},
	{
		id:15,
		text:'Bike',
		time:900,
		audio:'bike'
	},
	{
		id:16,
		text:'Treadmill',
		time:900,
		audio:'treadmill'
	},
	{
		id:17,
		text:'Arms/Shoulders',
		time:250,
	},
	{
		id:18,
		text:'Hammer Curl',
		time:120,
		audio:'hammerCurl'
	},
	{
		id:19,
		text:'Pull Up',
		time:60,
		audio:'pullup'
	},
	{
		id:20,
		text:'Push up',
		time:60,
		audio:'pushup'
	},
	{
		id:21,
		text:'Abs',
		time:190,
	},
	{
		id:22,
		text:'Crunches',
		time:60,
		audio:'crunches'
	},
	{
		id:23,
		text:'Plank',
		time:120,
		audio:'plank'
	},
	{
		id:24,
		text:'Warm Up',
		time:60,
		audio:'warmup'
	},
	{
		id:25,
		text:'Homework',
		time:3600,
		icon:'exam.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/homework',
			creator:'Freepik'
		}
	},
	{
		id:26,
		text:'Chores',
		time:3600,
		icon:'chores.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/cleaning',
			creator:'photo3idea_studio'
		}
	},
	{
		id:27,
		text:'Games/TV',
		time:3600,
		icon:'game.png',
		iconAttribution:{
			url:'https://www.flaticon.com/free-icons/board-game',
			creator:'Freepik'
		}
	},
	{
		id:28,
		text:'Technologic',
		audio:"technologic",
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		}
	},
	{
		id:29,
		text:'2 Legit 2 Quit',
		audio:"2legit",
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
	},
	{
		id:30,
		text:'Da Da Da',
	},
	{
		id:31,
		text:'Da Da Da',
		audio:"dadada1",
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
	},
	{
		id:32,
		text:"Ich lieb' dich nicht",
		audio:"dadada2",
		audioAttribution:{
			url:'https://freetts.com/',
			creator:'freetts.com'
		},
	}
];				